image: gradle:6.7-jdk15

stages:
  - build
  - staticAnalysis
  - test

variables:
  # Disable the Gradle daemon to ensure isolated runs of the CI pipeline.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

build-matcher-microservice:
  stage: build
  script:
    gradle matcher-microservice:assemble matcher-microservice:testClasses

checkStyle-matcher-microservice:
  stage: staticAnalysis
  script:
    gradle matcher-microservice:checkstyleMain matcher-microservice:checkStyleTest
  allow_failure: true


PMD-matcher-microservice:
  stage: staticAnalysis
  script:
    gradle matcher-microservice:pmdMain
  allow_failure: true

test-matcher-microservice:
  stage: test
  script:
    - gradle matcher-microservice:test matcher-microservice:jacocoTestReport
    - cat matcher-microservice/build/reports/jacoco/test/html/index.html | grep -Po "Total.*?([0-9]{1,3})%"
  coverage: /([0-9]{1,3})%/
